### PR TITLE
[network] add OSP external network for computes to diagram

### PR DESCRIPTION
**Pull request by stuggi**
Closes: https://github.com/openstack-k8s-operators/docs/issues/84

### CODE REVIEW

**Comment by karelyatin** [comment]
Looks good for compute nodes but i think we need that also on OCP Worker nodes too and ovn-controller pods will utilize that for SNAT traffic

**Comment by stuggi** [comment]
> Looks good for compute nodes but i think we need that also on OCP Worker nodes too and ovn-controller pods will utilize that for SNAT traffic

right, I'll update the PR for that

**Comment by stuggi** [comment]
updated, @karelyatin please have another look

**Pull request merged**
