### PR TITLE
Add a developer guide

### PR DESCRIPTION
**Pull request by gibizer**
Start documenting best practices / rule of thumbs for operator development. This patch also adds to guideline one for logging from the operator code and one for k8s client usage.

### CODE REVIEW

**Comment by abays** [comment]
We might also consider linking to the best practices docs: https://redhat-openshift-ecosystem.github.io/community-operators-prod/best-practices/

**Comment by gibizer** [comment]
> We might also consider linking to the best practices docs: https://redhat-openshift-ecosystem.github.io/community-operators-prod/best-practices/

Done.

**Review by stuggi — APPROVED** [review]
/lgtm thanks!

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
